version: '3.8'

services:
  # MCP Server service
  mcp-server:
    build:
      context: ./mcp_server
      dockerfile: Dockerfile
    container_name: uae-realestate-mcp-server
    restart: unless-stopped
    ports:
      - "${MCP_SERVER_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - VECTOR_DB_CONNECTION=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-vectordb}
      - BAYUT_API_KEY=${BAYUT_API_KEY}
      - PROPERTY_FINDER_API_KEY=${PROPERTY_FINDER_API_KEY}
      - DLD_API_KEY=${DLD_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY:-}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY:-}
      - LANGFUSE_HOST=${LANGFUSE_HOST:-https://cloud.langfuse.com}
    volumes:
      - mcp-server-logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - uae-realestate-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # PostgreSQL with pgvector extension
  postgres:
    image: ankane/pgvector:latest
    container_name: uae-realestate-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-vectordb}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - uae-realestate-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres-data:
    name: uae-realestate-postgres-data
  mcp-server-logs:
    name: uae-realestate-mcp-logs

networks:
  uae-realestate-network:
    name: uae-realestate-network
    driver: bridge
